---
# ************** Main Tasks **************** #
- hosts: main
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_pipelining: no
    sftp_batch_mode: yes

  vars_files:
    - /root/Migration-as-a-Service/src/northbound/config_files/migration/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service/etc/{{ tenant_name }}/{{ tenant_name }}C1.yml
  
  tasks:
  docker_container:
    name: t5_C1
    image: centos7
    state: stopped    
