---
- hosts: worker
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python2
  vars_files:
    - /root/Migration-as-a-Service-2.0/src/northbound/config_files/infrastructure/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service-2.0/etc/{{ tenant_name }}/{{ tenant_name }}c2.yml

  tasks:
  - name: Attach Container interface
    shell: |
      docker exec "{{ item.1.name }}" ip link show "{{ item.1.vmif }}" ; if [ $? -ne 0 ] ; then ip link set "{{ item.1.vmif }}" netns "{{ item.1.vm_pid }}" ; fi
    when:
      - item.1.brif != []
      - item.1.name != "JOKER"
      - item.1.vmif != []
      - item.1.vm_pid != []
    with_subelements:
      - "{{ Subnet }}"
      - vms

  - name: Make the container interface up
    shell: |
      docker exec "{{ item.1.name }}" ip link set dev "{{ item.1.vmif }}" up
    when:
      - item.1.brif != []
      - item.1.name != "JOKER"
      - item.1.vmif != []
      - item.1.vm_pid != []
    with_subelements:
      - "{{ Subnet }}"
      - vms

  - name: Run DHCLIENT
    shell: |
      docker exec "{{ item.1.name }}" ps aux | grep -w 'dhclient' | grep -w "{{ item.1.vmif }}" ; if [ $? -ne 0 ] ; then  docker exec "{{ item.1.name }}" dhclient "{{ item.1.vmif }}" ; fi
    when:
      - item.1.brif != []
      - item.1.name != "JOKER"
      - item.1.vmif != []
      - item.1.vm_pid != []
    with_subelements:
      - "{{ Subnet }}"
      - vms
