---
- hosts: worker
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python2
  vars_files:
    - /root/Migration-as-a-Service-2.0/src/northbound/config_files/infrastructure/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service-2.0/etc/{{ tenant_name }}/{{ tenant_name }}c2.yml

  tasks:
  - name: Build Docker Image
    docker_image:
      name: centos7
      build:
        path: /root/
      state: present
      source: build

  - name: Spawning Tenant Container
    docker_container:
      name: "{{ item.1.name }}"
      image: centos7:latest
      hostname: test
      privileged: yes
      interactive: yes
      tty: yes
    with_subelements:
      - "{{ Subnet }}"
      - vms
# ************************* Master tasks *********************** #
- hosts: main
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python2
  vars_files:
    - /root/Migration-as-a-Service-2.0/src/northbound/config_files/infrastructure/{{ tenant_name }}.yml
    - /root/Migration-as-a-Service-2.0/etc/{{ tenant_name }}/{{ tenant_name }}c1.yml

  tasks:
  - name: Run the Population script
    shell: |
      python3 /root/Migration-as-a-Service-2.0/src/logiclayer/parser_scripts/populate_container_pid.py "{{ tenant_name }}" "{{ tenant_name }}"c2.yml

  - pause:
      seconds: 15
