---
- hosts: localhost
  gather_facts: False
  
  tasks:
  - name: Pull tenant files
    git:
      repo: https://github.com/RamyaViju/Migration-as-a-Service-2.0.git
      dest: /root/
      update: yes
      clone: no
      version: master
    retries: 3
    register: result
    until: result is not failed
#    delay: 2
